### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArtemBernatskyy** [jrwashburn/mina-utils#1]
Hi, [in this case ](https://github.com/jrwashburn/mina-utils/blob/c522da47bee9f4c459ca2629dd69e66fccefb942/status-watchdog.sh#L40) our team just restarts daemon via `systemctl --user restart mina`.

Have you noticed pros and cons of just updating/checking for new peers?

**Comment by jrwashburn** [comment]
The daemon will stop after 15 minutes in status Offline on its own, so it should recycle by itself soon anyway. If there are new peers, there is a chance to get back in sync before having to restart. During testnet 4.1 I had experience successfully recovering without a restart by updating the peers. I decided to not restart immediately, but wait for the daemon to stop, and try to get new peers in the interim. 

I am logging the results of this (well, saving the stdout to a file) so I will be able to see in a few days whether or not it ever helped. If it doesn't, a more aggressive approach would be to just restart mina on the first detection. (I would still recommend updating the peer list before restart - in case there is a better peer-set at that point in time.)

**Comment by ArtemBernatskyy** [comment]
> The daemon will stop after 15 minutes in status Offline on its own

If we started mina daemon via

```
systemctl --user daemon-reload
systemctl --user start mina
systemctl --user enable mina
```

will it handle itself when left in `Offline` status, I mean will it auto restart or whetever?

Thx!

**Comment by jrwashburn** [comment]
It should. When daemon is Offline for 15 minutes, it should terminate, and then system should restart it again. Don’t forget to enable linger via loginctl.

On 1/3/21, 7:33 PM, "[Ar][Te]m.[Be][Rn][At]skyy" <notifications@github.com<mailto:notifications@github.com>> wrote:


The daemon will stop after 15 minutes in status Offline on its own

If we started mina daemon via

systemctl --user daemon-reload

systemctl --user start mina

systemctl --user enable mina

will it handle itself when left in Offline status, I mean will it auto restart or whetever?

Thx!

**Comment by ArtemBernatskyy** [comment]
Thx! One last question.

Can I run just Snark worker without BP in such case?

Edit: ah, I've realized that I can do that via just starting snark worker.
`/root/.config/systemd/user/multi-user.target.wants/mina.service` file gave me all answers

**Comment by jrwashburn** [comment]
I had an example of Offline overnight - the daemon did stop and restart on its own; and the watchdog did successfully download and add new peers. Adding new peers did not help to recover from offline.

**Comment by ArtemBernatskyy** [comment]
BTW @jrwashburn , I've checked your snark stopper implementation,
internally we are using average fees of top 50 (by fees earned) snark producers to set our snark fee,

what do you think of this ?

[here is our script](https://gist.github.com/ArtemBernatskyy/9259ff4fea21ba1656a22369379de32b)

**Comment by jrwashburn** [comment]
Just FYI - had another example of Offline overnight; however, this time the watchdog caught it, added peers, and recovered back to sync successfully.

**Comment by ArtemBernatskyy** [comment]
@jrwashburn [check this ](https://gist.github.com/ArtemBernatskyy/bdbd3d214cd5e1203d75bf8ee4c7ba1a) , it could be of some use,
it's the simplest simulation to find "fair" market price for transactions based on blockchain throughput and total number of transactions that accounts need to send till the end of challenge.
