### ISSUE TITLE
In new version (at least in my configuration) there is error with getting correct status

### ISSUE THREAD

**Issue by ArtemBernatskyy** [jrwashburn/mina-utils#4]
They added this text at the beginning `Using password from environment variable CODA_PRIVKEY_PASS`,
so it breaks [this line with](https://github.com/jrwashburn/mina-utils/blob/d03ae9bed2aac8440774665ad235dc4051d36caf/status-watchdog.sh#L22) with such error `parse error: Invalid numeric literal at line 1, column 6`

I've changed to `coda client status -json | awk '{if(NR>1)print}' | jq .sync_status` and it works.
P.S. I'm not sure if this only with my custom configuration, that's why I have not created a proper PR but raised an issue.

<img width="562" alt="imagen" src="https://user-images.githubusercontent.com/13070119/105613754-4b6c4e00-5dcd-11eb-9b50-34705b953f94.png">

**Comment by jrwashburn** [comment]
This is unique to your situation for some reason:
I still get "Synced" back from coda client status -json | jq .sync_status
I do not see "Using password from environment..." at all.
